server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:127.0.0.1:3306/sampledb?serverTimezone=Asia/Shanghai}
    username: ${DB_USER:demouser}
    password: ${DB_PASSWD:demopasswd}

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    # 打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    cache-enabled: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
# springdoc配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
